Hw 4 1 1
AlteragoPython/python_training pull request #7
Opened 2023-04-03 19:35 UTC by AlteragoPython

2023-04-04 08:07 UTC, alpakhomov requested changes
Тесты не проходят ни для одного из заданий, оставил комментарии

2023-04-04 08:07 UTC, alpakhomov commented on HW3_3.py
> +def custom_range(seq, start, stop=None, step=1):
В оригинальном файле с дз есть комментарий, в котором говорится что эта функция не должна использовать keyword аргументы.
Смысл этого задания в том чтобы придумать как передать необходимые параметры. Например можно так:
```py
def custom_range(seq, *args):
    ...
```
А внутри разобрать args - если длина == 1, то это стоп, если два - старт и стоп, и тд

2023-04-04 08:07 UTC, alpakhomov commented on HW4.py
> +        return solution
do_homework должен возвращать объект Result (имя может быть любое). В числе прочего в этом объекте должен быть записан автор.

2023-04-06 19:57 UTC, AlteragoPython commented on HW4.py
> +        return solution
pls review

2023-04-06 19:59 UTC, AlteragoPython commented on HW3_3.py
> +def custom_range(seq, start, stop=None, step=1):
pls review

2023-04-07 08:20 UTC, alpakhomov approved these changes

2023-04-24 16:32 UTC, merged